config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :samples

    root 'samples#index'
    get 'samples/:id/versions' => 'samples#versions' , as: :versions_sample

end

app/models/material_class.rb
class MaterialClass < ActiveRecord::Base
  has_paper_trail 
end

app/models/project.rb
class Project < ActiveRecord::Base
  #has_many :samples
  has_and_belongs_to_many :samples, join_table: :project_samples
  has_paper_trail 
  def name_and_code
    "#{name}-#{description}"
  end
end

app/models/sample.rb
class Sample < ActiveRecord::Base
  #validates :name, presence: true, uniqueness: true
  validates :tradename, presence: true
  validates :batch, presence: true
  validates_uniqueness_of :batch, scope: :tradename
  validates :parent_id, inclusion: {in: Sample.ids, message: "must be a registered batch - is #{parent}"}, allow_nil: true
  validates :primaryProject_id, inclusion: {in: Project.ids, message: 'must be an existing project'}, allow_nil: true
  validates :materialClass_id, inclusion: {in: MaterialClass.ids, message: 'must be a registered material class'}
  belongs_to :parent, class_name: 'Sample'
  has_many :children, class_name: 'Sample', :foreign_key => 'parent_id'
  belongs_to :materialClass
  has_and_belongs_to_many :projects, join_table: :project_samples
  belongs_to :primaryProject, class_name: 'Project'
  has_paper_trail 
  
  def tradename_and_batch
    "#{tradename}-#{batch}"
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_paper_trail 
  def is_goodyear?
    if /@goodyear\.com/.match(email)
      ret = true
    else
      ret = false
    end
    logger.debug "isgoodyear= #{ret}"
    ret
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def hello
    render html: "hello, world!"
  end
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only:[:edit, :update, :destroy, :new, :create]
  before_action :set_paper_trail_whodunnit
  # GET /samples
  # GET /samples.json
  def index
    @samples = Sample.all
  end

  # GET /samples/1
  # GET /samples/1.json
  def show
  end

  # GET /samples/new
  def new
    @sample = Sample.new
  end

  # GET /samples/1/edit
  def edit
  end

  # POST /samples
  # POST /samples.json
  def create
    logger.debug sample_params
    @sample = Sample.new(sample_params)

    respond_to do |format|
      if @sample.save
        @sample.sampleId="GYL-#{"%04d" % @sample.id}"
        @sample.save
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render :show, status: :created, location: @sample }
      else
        format.html { render :new }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    respond_to do |format|
      if @sample.update(sample_params)
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample }
      else
        format.html { render :edit }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url, notice: 'Sample was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def versions
    respond_to do |format|
      format.html { render :versions }
#      format.json { head :no_content }
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_params
      params.require(:sample).permit(:tradename, :batch, :parent_id, :origin, :materialClass_id, :comment, :provider, :primaryProject_id, :sampleId)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/layouts/_header.html.erb
  <header class="navbar navbar-fixed-top header">
    <div class="col-md-9 text-left"></div>
    <div class="col-md-3 text-right">
      <%= render 'layouts/user_widget' %>
    </div>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <p class="notice"><%= notice %></p>
  <title>Ligy</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
      <%= render 'layouts/header' %>
<div class="container-fluid">   
  <div class="row-fluid">
    <div class="span12 offset0">
      <%= yield %>
    </div>
  </div>
</div>
<%# render 'layouts/user_widget' %>
</body>
</html>

app/views/samples/_form.html.erb
<%= form_for(@sample) do |f| %>
  <% if @sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% @sample.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label @sample.id? ? true : false %><br>
    <%= f.text_field :sampleId, readonly: @sample.id ? true : false %>
  </div>
  <div class="field">
    <%= f.label :tradename %><br>
    <%= f.text_field :tradename %>
  </div>
  <div class="field">
    <%= f.label :batch %><br>
    <%= f.text_field :batch %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br>
    <%= f.collection_select(:parent_id, Sample.all, :id , :tradename_and_batch, { :prompt => 'select parent sample', :selected => @sample.parent},
        { class: 'form-control' }) %>
  </div>
  <div class="field">
    <%= f.label :origin %><br>
    <%= f.text_field :origin %>
  </div>
  <div class="field">
    <%= f.label :materialClass %><br>
    <%= f.collection_select(:materialClass_id, MaterialClass.all, :id , :name, { :prompt => 'select a material class', :selected => @sample.materialClass},
        { class: 'form-control' }) %>
  </div>
  <div class="field">
    <%= f.label :primaryProject %><br>
    <%= f.collection_select(:primaryProject_id, Project.all, :id , :name_and_code, { :prompt => 'select a project', :selected => @sample.primaryProject_id},
        { class: 'form-control' }) %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :provider %><br>
    <%= f.text_field :provider %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/samples/edit.html.erb
<h1>Editing Sample</h1>

<%= render 'form' %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Samples</h1>

<table class='table table-striped table-hover'>
  <thead>
    <tr>
      <th>Id</th>
      <th>Tradeame</th>
      <th>Batch</th>
      <th>Provider</th>
      <th>Parent</th>
      <th>Origin</th>
      <th>Material Class</th>
      <%if current_user && current_user.is_goodyear? %>
        <th>Comment</th>
      <% end %>

      <th>primary Project</th>
      <th>supplementary Projects</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @samples.each do |sample| %>
      <tr>
        <td><%= sample.sampleId %></td>
        <td><%= sample.tradename %></td>
        <td><%= sample.batch %></td>
        <td><%= sample.provider %></td>
        <td><%= sample.parent_id ? sample.parent.tradename_and_batch : '' %></td>
        <td><%= sample.origin %></td>
        <td><%= sample.materialClass ? sample.materialClass.name : '! material class lacking !' %></td>
        <%if current_user && current_user.is_goodyear? %>
          <td><%= sample.comment %></td>
        <%end%>
        <td><%= sample.primaryProject.name %></td>
        <td><%= sample.projects ? sample.projects.each {|proj| proj.name} : '! no project defined !' %></td>
        <td><%= link_to 'Show', sample %></td>
        <td><%= link_to 'Edit', edit_sample_path(sample) %></td>
        <td><%= link_to 'Destroy', sample, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sample', new_sample_path %>

app/views/samples/new.html.erb
<h1>New Sample</h1>

<%= render 'form' %>

<%= link_to 'Back', samples_path %>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sample Id:</strong>
  <%= @sample.sampleId %>
</p>

<p>
  <strong>Tradename:</strong>
  <%= @sample.tradename %>
</p>

<p>
  <strong>Batch:</strong>
  <%= @sample.batch %>
</p>

<p>
  <strong>parent:</strong>
  <%= @sample.tradename_and_batch %>
</p>

<p>
  <strong>Origin:</strong>
  <%= @sample.origin %>
</p>

<p>
  <strong>Material Class:</strong>
  <%= @sample.materialClass ? @sample.materialClass.name : '! Error : no material class defined !' %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @sample.comment %>
</p>

<p>
  <strong>Provider:</strong>
  <%= @sample.provider %>
</p>

<p>
  <strong>primary Project:</strong>
  <%= @sample.primaryProject ? @sample.primaryProject.name_and_code : '! no project defined !' %>
</p>

<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Versions', versions_sample_path(@sample) %> |
<%= link_to 'Back', samples_path %>

app/views/samples/versions.html.erb
<p id="notice"><%= notice %></p>

<h1>Versions for Sample <%= Sample.find(params[:id]).sampleId %></h1>

<table class='table table-striped table-hover'>
  <thead>
    <tr>
 <!--     <th>Object</th>
      <th>Id</th> -->
      <th>event</th>
      <th>User</th>
      <th>changes</th>
      <th>when</th>
    </tr>
  </thead>

  <tbody>
    <% Sample.find(params[:id]).versions.each do |version| %>
      
      <tr>
<!--        <td><%= version.item_type %></td>
        <td><%= version.item_id %></td>
-->        <td><%= version.event %></td>
        <td><%= User.find(version.whodunnit).email %></td>
        <td><%= version.changeset %></td>
        <td><%= version.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sample', new_sample_path %>
<%= link_to 'Back', samples_path %>